### PR TITLE
Readability Enhancements

### PR DESCRIPTION
**Pull request by ipnicholson**
## Reasoning

increase text sizes a few points for desktop and mobile to improve readability, add some padding to separate divs

### CODE REVIEW

**Comment by jeyip** [comment]
quick screenshot?

**Comment by ipnicholson** [comment]
screen shot 2017-12-12 at 12 39 19 pm 2
screen shot 2017-12-12 at 12 39 23 pm 2

**Comment by jeyip** [comment]
@ipnicholson Looks like the desktop layout is missing margins between the navigation cards and the notification bar

**Comment by jeyip** [comment]
@ipnicholson 

Also would it be possible to avoid the line break on the title and first navigation card? Trying to keep the contents above the fold on page load.

Maybe we can use less padding around the borders of the page.

**Comment by ipnicholson** [comment]
@jeyip That mobile view is iPhone SE, very narrow. Here's how it looks on iPhone 6. Acceptable?

screen shot 2017-12-12 at 12 43 42 pm 2

**Comment by ipnicholson** [comment]
`@ipnicholson Looks like the desktop layout is missing margins between the navigation cards and the notification bar`

@jeyip Added margin

screen shot 2017-12-12 at 12 47 59 pm 2

**Review by jeyip — APPROVED** [review]

**Pull request merged**
