### PR TITLE
Homepage: Add subheading, footer items

### PR DESCRIPTION
**Pull request by ipnicholson**
## Changes

1. Add "About Us" subheading
2. Remove "In case of emergency, call 911"
3. ^ Replace with "Homegrown in Ventura County // Part of the #805Strong network"

## Reasoning

Let users know who we are and what we're a part of.

## Screenshots

localhost_3000_ iphone 7 1
localhost_3000_ 1

### CODE REVIEW

**Comment by jeyip** [comment]
That's a lot of text in the mobile view. Could we put it under the navigation buttons?

**Review by mboperator — APPROVED** [review]

**Review by mboperator — COMMENTED** [review]
Design wise -- This is probably something that'd be better on the About page.

**Comment by jeyip** [comment]
Also, for the desktop view, could we bound the new text so that there's alignment with the other elements?

**Comment by mboperator** [comment]
I love `Homegrown in Ventura County`

How do you feel about removing the blurb up top altogether? 

We can maybe a message below the homegrown passage that links to the Wix site that Chris is working on.
IE: `Learn more about us`

**Review by mboperator — CHANGES_REQUESTED** [review]
Subheading is too large and probably belongs below the break

**Comment by jeyip** [comment]
I don't know about moving the blurb up top. The intention of the website is to get users to resources, so shouldn't the navigation buttons always be prominently visible first? Information about us should be secondary, but I'd be interested in what David thinks.

**Comment by ipnicholson** [comment]
@jeyip @mboperator 

Updated screenshots with subheading below nav buttons:
localhost_3000_ 2
localhost_3000_ iphone x

**Pull request merged**
